### ISSUE TITLE
Question: Is this tool capable of tailing IIS log files?

### ISSUE THREAD

**Issue by normanhh3** [OctopusDeploy/SeqFlatFileImport#2]
Is this tool capable of exporting live data over to Seq from IIS log files or is this designed for processing already closed out (i.e. previous day) log files using a scheduled task?

**Comment by droyad** [comment]
@normanhh3 Sorry for the slow delay, I forgot to watch this repo. 

My intention was to allow tailing, but I did not get to it, and I don't have a need for it at the moment. I will happily accept a PR with that feature though.

**Comment by normanhh3** [comment]
Thanks for the feedback. :-)
